### ISSUE TITLE
Whitepawn moves Bitboard value index 55 is out of range

### ISSUE THREAD

**Issue by materoy** [bhlangonijr/chesslib#106]
The line in [Bitboard.java](https://github.com/bhlangonijr/chesslib/blob/49599909c02fc652b15d89048ec88f8b707facf6/src/main/java/com/github/bhlangonijr/chesslib/Bitboard.java#L204) 

`0x8000000000000000L` when converted to kotlin results in an overflow error. 

Long max value in hex is 0x7FFFFFFFFFFFFFFF

Requesting for comment about this.

**Comment by materoy** [comment]
Why ?

**Comment by bhlangonijr** [comment]
I think you might be confused in thinking that `0x7FFFFFFFFFFFFFFF` > `0x8000000000000000L`. It is not.

`0x8000000000000000L` =  `0x7FFFFFFFFFFFFFFF + 1` which is greater than `Long.MAX_VALUE` and that's why you get the error out of range.

Kotlin introduces unsigned long (ULong) which is not present in Java.  In java `0x8000000000000000L` = `-9223372036854775808`. In Kotlin ULong `0x8000000000000000UL` = `9223372036854775808`.
